# languages.py

TRANSLATIONS = {
    "English": {
        # Navigation
        "nav_intro": "CardioPulse AI",
        "nav_auth": "Login/Register",
        "nav_dash": "Dashboard",
        "nav_input": "Health Details",
        "nav_results": "Graph & Report",
        "nav_settings": "Settings",
        "goto": " ",
        "user_lbl": "User:",
        "locked_warn": " Diagnostic functions locked. Authenticate via Login.",
        # Buttons & Statuses
        "btn_apply": "Apply Engine Configuration Adjustments",
        "btn_login": "Sign-In",
        "btn_register": "Register",
        "btn_evaluate": "Run Analytical Evaluation",
        "btn_parse": "Parse and Extract From Uploaded File",
        "btn_download": "Download Medical Assessment Report (PDF)",
        "logout_btn": "Logout",
        "success_reg": "Registration complete! Switch to Sign In tab to enter.",
        "success_login": "Login successful!",
        "success_param": "Calculated parameters locked successfully!",
        "success_file": "File processed completely!",
        "err_fill": "Please fill in all details.",
        "err_login": "Invalid username or password configuration.",
        # Page 1: Intro
        "intro_title": "Intelligent Cardiovascular Assessment Portal",
        "intro_p1": "Welcome to the unified analytics node for acute myocardial infarction diagnostics.",
        "intro_h3": "Core Functional Modules:",
        "intro_li1": "* **Secure Clinical Accounts:** Register or access your system configurations.",
        "intro_li2": "* **Dual Diagnostics Pipeline:** Predict manually or parse via automated report upload mechanics.",
        "intro_li3": "* **Global Configurations Module:** Adjust interface parameters in real-time from the pre-login Settings block.",
        # Page 2: Auth
        "auth_title": " Account Sign-In/ Login",
        "tab_signin": " Sign In ",
        "tab_signup": "Register New Profile",
        "lbl_fullname": "Full Name",
        "lbl_choose_user": "Choose Username",
        "lbl_choose_pass": "Choose Password",
        "lbl_user": "Username",
        "lbl_pass": "Password",
        # Page 3: Dashboard
        "dash_title": "Model Precision & Evaluation Console",
        "m_auc": "Production Engine AUC",
        "m_size": "Observations Record Size",
        "m_latency": "Latency Window",
        "m_stable": "Stable Release",
        "m_cases": "4,200 Cases",
        "m_ms": "42 ms",
        # Page 4: Patient Input
        "input_title": "Patient Health Vector Ingestion",
        "tab_manual": "Manual Clinical Entry",
        "tab_upload": "Document Report Upload",
        "form_subtitle": "Cardiovascular Attribute Metrics Form",
        "age": "Age", "gender": "Gender", "cp": "Chest Pain Type (cp)", "trestbps": "Resting BP (trestbps in mm Hg)",
        "chol": "Serum Cholesterol (chol in mg/dl)", "fbs": "Fasting Blood Sugar > 120 mg/dl (fbs)",
        "restecg": "Resting ECG Results (restecg)", "thalach": "Max Heart Rate Achieved (thalach)",
        "exang": "Exercise Induced Angina (exang)", "oldpeak": "ST Depression Induced by Exercise (oldpeak)",
        "slope": "Slope of Peak Exercise ST Segment (slope)", "ca": "Major Vessels Colored by Fluoroscopy (ca)",
        "thal": "Thalassemia Type (thal)", "male": "Male", "female": "Female", "true_lbl": "True", "false_lbl": "False",
        "drop_file": "Drop clinic PDF, TXT or CSV sheets here",
        # Page 5: Results
        "results_title": " Diagnostic Hazard Assessment & Guidelines",
        "risk_high": "Target system classification hazard index identifies at ",
        "risk_prob": "% Risk Probability",
        "graph_risk": "Heart Risk %", "graph_clean": "Healthy Heart %",
        "status_lbl": "Status", "prob_lbl": "Probability",
        "food_title": "Target Food Habit & Nutrition Protocols",
        "food_li1": "* Increase oats and Viscous Fiber consumption.\n* Switch lipids completely to extra virgin olive oil.\n* Restrict salt ingestion below 1,500mg daily.",
        "doc_title": " Medical Specialist Lookup Engine",
        "btn_google": " Launch External Cardiologist Search Directory",
        "export_title": " Export Diagnostic Documentation",
        "export_p": "Generate and download a hard copy breakdown of this analysis for your clinical records:",
        "note_text": "**Note:** No fully Trust this report. This is AI generated and predicted one. So, Use this report and discuss with your nearby hospitals or ask the opinon with your`s family doctor.",
        # Settings
        "settings_title": " System Control & Interface Settings",
        "settings_p": "Configure application display preferences and view profile sessions.",
        "set_sub1": " Localization & Personalization",
        "set_lang_lbl": "System Primary Language Selection",
        "set_theme_lbl": "Visual Workspace Theme Profile",
        "set_sub2": " User Session Status Profile",
        "set_auth_name": "**Authenticated Fullname:** ",
        "set_role": "Role assigned: Clinical Core Operator",
        "set_no_profile": "No active profile detected. Please complete account sign-in.",
        "set_refresh": "Visual styles refreshed! Rerunning app...",
        "tab_google": "Google Login",
        "lbl_g_email": "Enter Your Real Google Account Email Address",
        "btn_g_auth": "Login with Google"
    },
    "Tamil (தமிழ்)": {
        # Navigation
        "nav_intro": "CardioPulse AI",
        "nav_auth": "உள்நுழைவு/பதிவு",
        "nav_dash": "டாஷ்போர்டு",
        "nav_input": "உடல்நல விவரங்கள்",
        "nav_results": "வரைபடம் & அறிக்கை",
        "nav_settings": "அமைப்புகள்",
        "goto": " ",
        "user_lbl": "பயனர்:",
        "locked_warn": " கண்டறியும் செயல்பாடுகள் பூட்டப்பட்டுள்ளன. உள்நுழைவு (Login) வழியாக அங்கீகரிக்கவும்.",
        # Buttons & Statuses
        "btn_apply": "அமைப்புகளைப் பயன்படுத்துக",
        "btn_login": "உள்நுழைக",
        "btn_register": "பதிவு செய்க",
        "btn_evaluate": "பகுப்பாய்வு மதிப்பீட்டை இயக்குக",
        "btn_parse": "பதிவேற்றிய கோப்பிலிருந்து பகுப்பாய்வு செய்க",
        "btn_download": "மருத்துவ அறிக்கையைப் பதிவிறக்கு (PDF)",
        "logout_btn": "வெளியேறு",
        "success_reg": "பதிவு முடிந்தது! உள்நுழைய 'உள்நுழைவு' தாவலுக்கு மாறவும்.",
        "success_login": "உள்நுழைவு வெற்றிகரமாக முடிந்தது!",
        "success_param": "கணக்கிடப்பட்ட அளவுருக்கள் வெற்றிகரமாக பூட்டப்பட்டன!",
        "success_file": "கோப்பு முழுமையாக செயலாக்கப்பட்டது!",
        "err_fill": "அனைத்து விவரங்களையும் நிரப்பவும்.",
        "err_login": "தவறான பயனர் பெயர் அல்லது கடவுச்சொல் அமைப்பு.",
        # Page 1: Intro
        "intro_title": "அறிவார்ந்த இதய நோய் மதிப்பீட்டு மையம்",
        "intro_p1": "இதய தசைநார் அழற்சி கண்டறிதலுக்கான ஒருங்கிணைந்த பகுப்பாய்வு மையத்திற்கு உங்களை வரவேற்கிறோம்.",
        "intro_h3": "முக்கிய செயல்பாட்டு தொகுதிகள்:",
        "intro_li1": "* **பாதுகாப்பான மருத்துவ கணக்குகள்:** கணினியை அணுக உங்கள் கணக்கை பதிவு செய்யவும்.",
        "intro_li2": "* **இரட்டை கண்டறிதல் முறை:** தரவுகளை கைமுறையாக உள்ளிடவும் அல்லது தானியங்கி அறிக்கை பதிவேற்றத்தைப் பயன்படுத்தவும்.",
        "intro_li3": "* **உலகளாவிய அமைப்புகள் தொகுதி:** அமைப்புகள் பக்கத்திலிருந்து இடைமுக விருப்பங்களை உடனுக்குடன் மாற்றியமைக்கவும்.",
        # Page 2: Auth
        "auth_title": "கணக்கு உள்நுழைவு மற்றும் சரிபார்ப்பு",
        "tab_signin": "உள்நுழைதல்",
        "tab_signup": "புதிய சுயவிவரத்தை பதிவு செய்க",
        "lbl_fullname": "முழு பெயர்",
        "lbl_choose_user": "பயனர் பெயரைத் தேர்ந்தெடுக்கவும்",
        "lbl_choose_pass": "கடவுச்சொல்லைத் தேர்ந்தெடுக்கவும்",
        "lbl_user": "பயனர் பெயர்",
        "lbl_pass": "கடவுச்சொல்",
        # Page 3: Dashboard
        "dash_title": "AI மாதிரியின் துல்லிய கணக்கீட்டு மேடை",
        "m_auc": "உற்பத்தி மாதிரியின் துல்லியம் (AUC)",
        "m_size": "சேகரிக்கப்பட்ட தரவுகளின் அளவு",
        "m_latency": "பகுப்பாய்வு எடுக்கும் நேரம்",
        "m_stable": "நிலையான வெளியீடு",
        "m_cases": "4,200 வழக்குகள்",
        "m_ms": "42 மில்லி விநாடிகள்",
        # Page 4: Patient Input
        "input_title": "நோயாளி உடல்நல தரவு உள்ளீடு",
        "tab_manual": "கைமுறை மருத்துவ உள்ளீடு",
        "tab_upload": "மருத்துவ அறிக்கை பதிவேற்றம்",
        "form_subtitle": "இதய ஆரோக்கிய அளவுருக்கள் படிவம்",
        "age": "வயது", "gender": "பாலினம்", "cp": "நெஞ்சு வலி வகை (cp)", "trestbps": "இரத்த அழுத்தம் (trestbps - mm Hg)",
        "chol": "கொலஸ்ட்ரால் அளவு (chol - mg/dl)", "fbs": "உண்ணாவிரத இரத்த சர்க்கரை > 120 mg/dl (fbs)",
        "restecg": "இதய மின்வரைபடம் (restecg)", "thalach": "அடைந்த அதிகபட்ச இதய துடிப்பு (thalach)",
        "exang": "உடற்பயிற்சியால் ஏற்படும் நெஞ்சுவலி (exang)", "oldpeak": "இதய தசை சோர்வு நிலை (oldpeak)",
        "slope": "உடற்பயிற்சி எஸ்டி பிரிவின் சாய்வு (slope)", "ca": "முக்கிய இரத்த நாளங்களின் எண்ணிக்கை (ca)",
        "thal": "தலசீமியா பாதிப்பு வகை (thal)", "male": "ஆண்", "female": "பெண்", "true_lbl": "உண்மை", "false_lbl": "பொய்",
        "drop_file": "மருத்துவமனை PDF, TXT அல்லது CSV கோப்புகளை இங்கே பதிவேற்றவும்",
        # Page 5: Results
        "results_title": "கண்டறிதல் ஆபத்து மதிப்பீடு மற்றும் வழிகாட்டுதல்கள்",
        "risk_high": "கணினி பகுப்பாய்வின்படி தங்களுக்கு இதய நோய் வரக்கூடிய சாத்தியக்கூறு: ",
        "risk_prob": "% ஆபத்து வாய்ப்பு",
        "graph_risk": "இதய பாதிப்பு வாய்ப்பu %", "graph_clean": "ஆரோக்கியமான இதயம் %",
        "status_lbl": "நிலை", "prob_lbl": "சதவீதம்",
        "food_title": "உணவுப் பழக்கம் மற்றும் ஊட்டச்சத்து வழிகாட்டுதல்கள்",
        "food_li1": "* ஓட்ஸ் மற்றும் நார்ச்சத்து நிறைந்த உணவுகளை அதிகமாக உட்கொள்ளுங்கள்.\n* சமையலுக்கு கூடுதல் கன்னி ஆலிவ் எண்ணெயை (Olive Oil) மட்டுமே பயன்படுத்தவும்.\n* தினசரி உப்பு உட்கொள்ளலை 1,500 மில்லிகிராமிற்குள் கட்டுப்படுத்துங்கள்.",
        "doc_title": "இதய நோய் நிபுணர் தேடல் பொறி",
        "btn_google": "கூகிள் தேடல் மூலம் இதய நிபுணர்களைக் கண்டறியவும்",
        "export_title": "மருத்துவ அறிக்கையைப் பதிவிறக்கம் செய்தல்",
        "export_p": "உங்கள் மருத்துவ பதிவுகளுக்காக இந்த பகுப்பாய்வின் நகலை PDF வடிவில் பதிவிறக்கம் செய்து கொள்ளுங்கள்:",
        "note_text": "**குறிப்பு:** இந்த அறிக்கையை முழுமையாக நம்ப வேண்டாம். இது AI மூலம் உருவாக்கப்பட்டு கணிக்கப்பட்டது. எனவே, இந்த அறிக்கையைப் பயன்படுத்தி உங்கள் அருகில் உள்ள மருத்துவமனைகளில் விவாதிக்கவும் அல்லது உங்கள் குடும்ப மருத்துவரிடம் ஆலோசனை பெறவும்.",
        # Settings
        "settings_title": "கணினி கட்டுப்பாடு மற்றும் இடைமுக அமைப்புகள்",
        "settings_p": "பயன்பாட்டின் காட்சி விருப்பங்களை உள்ளமைக்கவும் மற்றும் பயனர் அமர்வுகளைக் காணவும்.",
        "set_sub1": "உள்ளூர்மயமாக்கல் மற்றும் தனிப்பயனாக்கம்",
        "set_lang_lbl": "முதன்மை மொழி தேர்வு (Language)",
        "set_theme_lbl": "பக்கத்தின் வண்ணத் தீம் (Theme Profile)",
        "set_sub2": "பயனர் கணக்கு நிலை விவரம்",
        "set_auth_name": "**உள்நுழைந்தவரின் பெயர்:** ",
        "set_role": "அங்கீகரிக்கப்பட்ட பயனர்: முதன்மை மருத்துவ ஆபரேட்டர்",
        "set_no_profile": "செயலில் உள்ள சுயவிவரம் எதுவும் கண்டறியப்படவில்லை. கணக்கு உள்நுழைவை நிறைவு செய்யவும்.",
        "set_refresh": "காட்சி அமைப்புகள் புதுப்பிக்கப்பட்டன! மீண்டும் தொடங்குகிறது...",
        "tab_google": "கூகிள் உள்நுழைவு",
        "lbl_g_email": "உங்கள் உண்மையான கூகிள் கணக்கு மின்னஞ்சல் முகவரியை உள்ளிடவும்",
        "btn_g_auth": "கூகிள் மூலம் உள்நுழைக"
    },
    "Español": {
        # Navigation
        "nav_intro": "CardioPulse AI",
        "nav_auth": "Iniciar Sesión/Registrarse",
        "nav_dash": "Panel de Control",
        "nav_input": "Detalles de Salud",
        "nav_results": "Gráfica y Reporte",
        "nav_settings": "Configuración",
        "goto": " ",
        "user_lbl": "Usuario:",
        "locked_warn": " Funciones de diagnóstico bloqueadas. Autentíquese a través de Login.",
        # Buttons & Statuses
        "btn_apply": "Aplicar Ajustes de Configuración",
        "btn_login": "Iniciar Sesión",
        "btn_register": "Registrarse",
        "btn_evaluate": "Ejecutar Evaluación Analítica",
        "btn_parse": "Procesar y Extraer del Archivo Cargado",
        "btn_download": "Descargar Reporte de Evaluación Médica (PDF)",
        "logout_btn": "Cerrar Sesión",
        "success_reg": "¡Registro completo! Cambie a la pestaña Iniciar Sesión.",
        "success_login": "¡Inicio de sesión exitoso!",
        "success_param": "¡Parámetros calculados guardados con éxito!",
        "success_file": "¡Archivo procesado por completo!",
        "err_fill": "Por favor complete todos los detalles.",
        "err_login": "Configuración de usuario o contraseña inválida.",
        # Page 1: Intro
        "intro_title": "Portal de Evaluación Cardiovascular Inteligente",
        "intro_p1": "Bienvenido al nodo analítico unificado para el diagnóstico de infarto agudo de miocardio.",
        "intro_h3": "Módulos Funcionales Clave:",
        "intro_li1": "* **Cuentas Clínicas Seguras:** Regístrese o acceda a sus configuraciones.",
        "intro_li2": "* **Línea de Diagnóstico Dual:** Prediga manualmente o mediante carga automatizada de reportes.",
        "intro_li3": "* **Módulo de Configuración Global:** Ajuste parámetros en tiempo real desde el bloque de Configuración.",
        # Page 2: Auth
        "auth_title": "Inicio de Sesión / Acceso de Cuenta",
        "tab_signin": "Iniciar Sesión",
        "tab_signup": "Registrar Nuevo Perfil",
        "lbl_fullname": "Nombre Completo",
        "lbl_choose_user": "Elegir Usuario",
        "lbl_choose_pass": "Elegir Contraseña",
        "lbl_user": "Usuario",
        "lbl_pass": "Contraseña",
        # Page 3: Dashboard
        "dash_title": "Consola de Evaluación y Precisión del Modelo",
        "m_auc": "AUC del Motor de Producción",
        "m_size": "Tamaño del Registro de Observaciones",
        "m_latency": "Ventana de Latencia",
        "m_stable": "Versión Estable",
        "m_cases": "4,200 Casos",
        "m_ms": "42 ms",
        # Page 4: Patient Input
        "input_title": "Ingesta de Vectores de Salud del Paciente",
        "tab_manual": "Entrada Clínica Manual",
        "tab_upload": "Carga de Reporte Documental",
        "form_subtitle": "Formulario de Métricas de Atributos Cardiovasculares",
        "age": "Edad", "gender": "Género", "cp": "Tipo de Dolor Torácico (cp)", "trestbps": "PA en Reposo (trestbps en mm Hg)",
        "chol": "Colesterol Sérico (chol en mg/dl)", "fbs": "Glucemia en Ayunas > 120 mg/dl (fbs)",
        "restecg": "Resultados del ECG en Reposo (restecg)", "thalach": "Frecuencia Cardíaca Máxima (thalach)",
        "exang": "Angina Inducida por Ejercicio (exang)", "oldpeak": "Depresión del ST por Ejercicio (oldpeak)",
        "slope": "Pendiente del Segmento ST (slope)", "ca": "Vasos Mayores Coloreados (ca)",
        "thal": "Tipo de Talasemia (thal)", "male": "Masculino", "female": "Femenino", "true_lbl": "Verdadero", "false_lbl": "Falso",
        "drop_file": "Arrastre aquí sus hojas clínicas en PDF, TXT o CSV",
        # Page 5: Results
        "results_title": "Evaluación de Riesgos Diagnósticos y Pautas",
        "risk_high": "El índice de riesgo de clasificación identifica un ",
        "risk_prob": "% de Probabilidad de Riesgo",
        "graph_risk": "Riesgo Cardíaco %", "graph_clean": "Corazón Sano %",
        "status_lbl": "Estado", "prob_lbl": "Probabilidad",
        "food_title": "Protocolos de Nutrición y Hábitos Alimenticios",
        "food_li1": "* Aumente el consumo de avena y fibra soluble.\n* Sustituya grasas usando aceite de oliva virgen extra.\n* Restrinja la ingesta de sal por debajo de 1,500 mg diarios.",
        "doc_title": "Motor de Búsqueda de Especialistas Médicos",
        "btn_google": "Buscar Cardiólogos en Directorio Externo",
        "export_title": "Exportar Documentación Diagnóstica",
        "export_p": "Genere y descargue una copia física de este análisis para sus registros clínicos:",
        "note_text": "**Nota:** No confíe completamente en este informe. Este es un resultado generado y predicho por IA. Por lo tanto, use este informe para discutirlo con sus hospitales cercanos o solicite la opinión de su médico de cabecera.",
        # Settings
        "settings_title": "Configuración del Sistema e Interfaz",
        "settings_p": "Configure las preferencias de visualización y vea las sesiones de perfil.",
        "set_sub1": "Localización y Personalización",
        "set_lang_lbl": "Selección de Idioma Principal del Sistema",
        "set_theme_lbl": "Perfil de Tema del Espacio de Trabajo",
        "set_sub2": "Perfil de Estado de Sesión de Usuario",
        "set_auth_name": "**Nombre Completo Autenticado:** ",
        "set_role": "Rol asignado: Operador Central Clínico",
        "set_no_profile": "No se detectó ningún perfil activo. Complete el inicio de sesión de la cuenta.",
        "set_refresh": "¡Estilos visuales actualizados! Reiniciando la app...",
        "tab_google": "Iniciar sesión con Google",
        "lbl_g_email": "Ingrese su dirección de correo electrónico real de Google",
        "btn_g_auth": "Iniciar sesión con Google"
    },
    "Français": {
        # Navigation
        "nav_intro": "CardioPulse AI",
        "nav_auth": "Connexion/Inscription",
        "nav_dash": "Tableau de Bord",
        "nav_input": "Données de Santé",
        "nav_results": "Graphique & Rapport",
        "nav_settings": "Paramètres",
        "goto": " ",
        "user_lbl": "Utilisateur :",
        "locked_warn": " Fonctions de diagnostic verrouillées. Authentifiez-vous via Login.",
        # Buttons & Statuses
        "btn_apply": "Appliquer les Modifications de Configuration",
        "btn_login": "Connexion",
        "btn_register": "S'inscrire",
        "btn_evaluate": "Lancer l'Évaluation Analytique",
        "btn_parse": "Analyser et Extraire du Fichier Téléversé",
        "btn_download": "Télécharger le Rapport d'Évaluation Médicale (PDF)",
        "logout_btn": "Déconnexion",
        "success_reg": "Inscription réussie ! Passez à l'onglet Connexion.",
        "success_login": "Connexion réussie !",
        "success_param": "Paramètres calculés verrouillés avec succès !",
        "success_file": "Fichier traité avec succès !",
        "err_fill": "Veuillez remplir tous les champs.",
        "err_login": "Identifiant ou mot de passe invalide.",
        # Page 1: Intro
        "intro_title": "Portail d'Évaluation Cardiovasculaire Intelligent",
        "intro_p1": "Bienvenue sur la plateforme unifiée d'analyse pour le diagnostic de l'infarctus aigu du myocarde.",
        "intro_h3": "Modules Fonctionnels Principaux :",
        "intro_li1": "* **Comptes Cliniques Sécurisés :** Enregistrez-vous ou accédez à vos configurations.",
        "intro_li2": "* **Pipeline de Diagnostic Double :** Prédiction manuelle ou via téléversement de rapport médical.",
        "intro_li3": "* **Module de Configuration Globale :** Ajustez les paramètres en temps réel depuis l'espace Paramètres.",
        # Page 2: Auth
        "auth_title": "Connexion au Compte / Accès",
        "tab_signin": "Se Connecter",
        "tab_signup": "Créer Nouveau Profil",
        "lbl_fullname": "Nom Complet",
        "lbl_choose_user": "Choisir un Identifiant",
        "lbl_choose_pass": "Choisir un Mot de Passe",
        "lbl_user": "Identifiant",
        "lbl_pass": "Mot de Passe",
        # Page 3: Dashboard
        "dash_title": "Console de Précision & d'Évaluation du Modèle",
        "m_auc": "AUC du Moteur de Production",
        "m_size": "Taille du Registre des Observations",
        "m_latency": "Fenêtre de Latence",
        "m_stable": "Version Stable",
        "m_cases": "4,200 Cas",
        "m_ms": "42 ms",
        # Page 4: Patient Input
        "input_title": "Ingestion des Vecteurs de Santé du Patient",
        "tab_manual": "Saisie Clinique Manuelle",
        "tab_upload": "Téléversement de Rapport Médical",
        "form_subtitle": "Formulaire des Métriques Cardiovasculaires",
        "age": "Âge", "gender": "Genre", "cp": "Type de Douleur Thoracique (cp)", "trestbps": "PA au Repos (trestbps en mm Hg)",
        "chol": "Cholestérol Sérique (chol en mg/dl)", "fbs": "Glycémie à Jeun > 120 mg/dl (fbs)",
        "restecg": "Résultats de l'ECG au Repos (restecg)", "thalach": "Fréquence Cardiaque Maximale (thalach)",
        "exang": "Angine Inducida par l'Exercice (exang)", "oldpeak": "Dépression du ST par l'Exercice (oldpeak)",
        "slope": "Pente du Segment ST (slope)", "ca": "Nombre de Vaisseaux Majeurs (ca)",
        "thal": "Type de Thalassémie (thal)", "male": "Masculin", "female": "Féminin", "true_lbl": "Vrai", "false_lbl": "Faux",
        "drop_file": "Déposez vos fichiers cliniques PDF, TXT ou CSV ici",
        # Page 5: Results
        "results_title": "Évaluation des Risques Diagnostiques & Directives",
        "risk_high": "L'indice de classification des risques identifie un ",
        "risk_prob": "% de Pourcentage de Risque",
        "graph_risk": "Risque Cardiaque %", "graph_clean": "Cœur Sain %",
        "status_lbl": "Statut", "prob_lbl": "Probabilité",
        "food_title": "Protocoles de Nutrition & Habitudes Alimentaires",
        "food_li1": "* Augmentez la consommation d'avoine et de fibres solubles.\n* Remplacez les graisses par de l'huile d'olive vierge extra.\n* Limitez l'apport en sel en dessous de 1 500 mg par jour.",
        "doc_title": "Moteur de Recherche de Spécialistes Médicaux",
        "btn_google": "Rechercher des Cardiologues sur un Répertoire Externe",
        "export_title": "Exporter la Documentation Diagnostique",
        "export_p": "Générez et téléchargez une copie papier de cette analysis pour vos dossiers médicaux :",
        "note_text": "**Note :** Ne vous fiez pas entièrement à ce rapport. Il s'agit d'un résultat généré et prédit par IA. Par conséquent, utilisez ce rapport pour en discuter avec les hôpitaux proches ou demandez l'avis de votre médecin de famille.",
        # Settings
        "settings_title": "Contrôle du Système & Paramètres de l'Interface",
        "settings_p": "Configurez les préférences d'affichage et gérez les sessions de profil.",
        "set_sub1": "Localisation & Personnalisation",
        "set_lang_lbl": "Sélection de la Langue Principale du Système",
        "set_theme_lbl": "Profil de Thème de l'Espace de Travail",
        "set_sub2": "Profil de Statut de la Session Utilisateur",
        "set_auth_name": "**Nom Complet Authentifié :** ",
        "set_role": "Rôle attribué : Opérateur Clinique Principal",
        "set_no_profile": "Aucun profil actif détecté. Veuillez compléter la connexion au compte.",
        "set_refresh": "Styles visuels mis à jour ! Relancement de l'application...",
        "tab_google": "Connexion Google",
        "lbl_g_email": "Saisissez votre véritable adresse e-mail Google",
        "btn_g_auth": "Se connecter avec Google"
    },
    "Deutsch": {
        # Navigation
        "nav_intro": "CardioPulse AI",
        "nav_auth": "Anmelden/Registrieren",
        "nav_dash": "Dashboard",
        "nav_input": "Gesundheitsdaten",
        "nav_results": "Diagramm & Bericht",
        "nav_settings": "Einstellungen",
        "goto": " ",
        "user_lbl": "Benutzer:",
        "locked_warn": " Diagnosefunktionen gesperrt. Bitte authentifizieren Sie sich über Login.",
        # Buttons & Statuses
        "btn_apply": "Konfigurationsänderungen übernehmen",
        "btn_login": "Anmelden",
        "btn_register": "Registrieren",
        "btn_evaluate": "Analytische Auswertung starten",
        "btn_parse": "Daten aus hochgeladener Datei extrahieren",
        "btn_download": "Medizinischen Bewertungsbericht herunterladen (PDF)",
        "logout_btn": "Abmelden",
        "success_reg": "Registrierung abgeschlossen! Wechseln Sie zum Reiter 'Anmelden'.",
        "success_login": "Anmeldung erfolgreich!",
        "success_param": "Berechnete Parameter erfolgreich gespeichert!",
        "success_file": "Datei erfolgreich verarbeitet!",
        "err_fill": "Bitte füllen Sie alle Felder aus.",
        "err_login": "Ungültiger Benutzername oder falsches Passwort.",
        # Page 1: Intro
        "intro_title": "Intelligentes Portal zur kardiovaskulären Bewertung",
        "intro_p1": "Willkommen auf der zentralen Analyseplattform für die Diagnostik des akuten Myokardinfarkts.",
        "intro_h3": "Wesentliche Funktionsmodule:",
        "intro_li1": "* **Sichere klinische Konten:** Registrieren Sie sich oder greifen Sie auf Ihre Konfigurationen zu.",
        "intro_li2": "* **Duales Diagnosesystem:** Manuelle Eingabe oder automatisierter Import von medizinischen Berichten.",
        "intro_li3": "* **Globales Konfigurationsmodul:** Passen Sie Schnittstellenparameter in Echtzeit im Einstellungsbereich an.",
        # Page 2: Auth
        "auth_title": "Konto-Anmeldung / Zugang",
        "tab_signin": "Anmelden",
        "tab_signup": "Neues Profil registrieren",
        "lbl_fullname": "Vollständiger Name",
        "lbl_choose_user": "Benutzername wählen",
        "lbl_choose_pass": "Passwort wählen",
        "lbl_user": "Benutzername",
        "lbl_pass": "Passwort",
        # Page 3: Dashboard
        "dash_title": "Modellpräzision & Analysekonsole",
        "m_auc": "Produktions-Engine AUC",
        "m_size": "Anzahl der Beobachtungen",
        "m_latency": "Latenzfenster",
        "m_stable": "Stabile Version",
        "m_cases": "4.200 Fälle",
        "m_ms": "42 ms",
        # Page 4: Patient Input
        "input_title": "Erfassung der Patientengesundheitsdaten",
        "tab_manual": "Manuelle klinische Eingabe",
        "tab_upload": "Upload von medizinischen Berichten",
        "form_subtitle": "Formular für kardiovaskuläre Merkmale",
        "age": "Alter", "gender": "Geschlecht", "cp": "Thoraxschmerz-Typ (cp)", "trestbps": "Blutdruck in Ruhe (trestbps in mm Hg)",
        "chol": "Serum-Cholesterin (chol in mg/dl)", "fbs": "Nüchternblutzucker > 120 mg/dl (fbs)",
        "restecg": "Ruhe-EKG-Ergebnisse (restecg)", "thalach": "Maximal erreichte Herzfrequenz (thalach)",
        "exang": "Belastungsinduzierte Angina Pectoris (exang)", "oldpeak": "ST-Depression durch Belastung (oldpeak)",
        "slope": "Steigung des Belastungs-ST-Segments (slope)", "ca": "Anzahl der Hauptgefäße (ca)",
        "thal": "Thalassämie-Typ (thal)", "male": "Männlich", "female": "Weiblich", "true_lbl": "Wahr", "false_lbl": "Falsch",
        "drop_file": "Ziehen Sie klinische PDF-, TXT- oder CSV-Dateien hierher",
        # Page 5: Results
        "results_title": "Diagnostische Risikobewertung & Richtlinien",
        "risk_high": "Der Klassifikations-Risikoindex zeigt eine ",
        "risk_prob": "% Risikowahrscheinlichkeit",
        "graph_risk": "Herzkrankheitsrisiko %", "graph_clean": "Gesundes Herz %",
        "status_lbl": "Status", "prob_lbl": "Wahrscheinlichkeit",
        "food_title": "Ernährungsprotokolle & Zielgerichtete Essgewohnheiten",
        "food_li1": "* Erhöhen Sie den Verzehr von Haferflocken und löslichen Ballaststoffen.\n* Ersetzen Sie Fette vollständig durch extra natives Olivenöl.\n* Reduzieren Sie die tägliche Salzaufnahme auf unter 1.500 mg.",
        "doc_title": "Suchmaschine für medizinische Spezialisten",
        "btn_google": "Kardiologen im externen Verzeichnis suchen",
        "export_title": "Diagnosedokumentation exportieren",
        "export_p": "Erstellen und laden Sie eine gedruckte Kopie dieser Analyse für Ihre Krankenakte herunter:",
        "note_text": "**Hinweis:** Vertrauen Sie diesem Bericht nicht blind. Dies ist ein KI-generiertes und prognostiziertes Ergebnis. Besprechen Sie diesen Bericht daher mit einem Krankenhaus in Ihrer Nähe oder holen Sie die Meinung Ihres Hausarztes ein.",
        # Settings
        "settings_title": "Systemsteuerung & Schnittstelleneinstellungen",
        "settings_p": "Konfigurieren Sie Anzeigeoptionen und verwalten Sie Profilsitzungen.",
        "set_sub1": "Lokalisierung & Personalisierung",
        "set_lang_lbl": "Primäre Sprachauswahl des Systems",
        "set_theme_lbl": "Workspace-Design-Profil",
        "set_sub2": "Statusprofil der Benutzersitzung",
        "set_auth_name": "**Authentifizierter vollständiger Name:** ",
        "set_role": "Zugewiesene Rolle: Klinischer Kernoperator",
        "set_no_profile": "Kein aktives Profil gefunden. Bitte schließen Sie die Kontoanmeldung ab.",
        "set_refresh": "Visuelle Stile aktualisiert! Anwendung wird neu gestartet...",
        "tab_google": "Google Login",
        "lbl_g_email": "Geben Sie Ihre echte Google-E-Mail-Adresse ein",
        "btn_g_auth": "Mit Google anmelden"
    },
    "Hindi (हिन्दी)": {
        # Navigation
        "nav_intro": "CardioPulse AI",
        "nav_auth": "लॉगिन/पंजीकरण",
        "nav_dash": "डैशबोर्ड",
        "nav_input": "स्वास्थ्य विवरण",
        "nav_results": "ग्राफ और रिपोर्ट",
        "nav_settings": "सेटिंग्स",
        "goto": " ",
        "user_lbl": "उपयोगकर्ता:",
        "locked_warn": " नैदानिक ​​कार्य लॉक हैं। कृपया लॉगिन (Login) के माध्यम से सत्यापित करें।",
        # Buttons & Statuses
        "btn_apply": "सिस्टम कॉन्फ़िगरेशन सेटिंग्स लागू करें",
        "btn_login": "साइन-इन",
        "btn_register": "पंजीकरण",
        "btn_evaluate": "विश्लेषणात्मक मूल्यांकन चलाएं",
        "btn_parse": "अपलोड की गई फ़ाइल से डेटा निकालें",
        "btn_download": "मेडिकल रिपोर्ट डाउनलोड करें (PDF)",
        "logout_btn": "लॉगआउट",
        "success_reg": "पंजीकरण पूरा हुआ! कृपया लॉगिन टैब पर जाएँ।",
        "success_login": "लॉगिन सफल रहा!",
        "success_param": "गणना किए गए पैरामीटर सफलतापूर्वक लॉक किए गए!",
        "success_file": "फ़ाइल पूरी तरह से संसाधित हो गई है!",
        "err_fill": "कृपया सभी विवरण भरें।",
        "err_login": "अमान्य उपयोगकर्ता नाम या पासवर्ड कॉन्फ़िगरेशन।",
        # Page 1: Intro
        "intro_title": "इंटेलिजेंट कार्डियोवस्कुलर असेसमेंट पोर्टल",
        "intro_p1": "एक्यूट मायोकार्डियल इन्फार्क्शन (हार्ट अटैक) निदान के लिए एकीकृत विश्लेषण केंद्र में स्वागत है।",
        "intro_h3": "मुख्य कार्यात्मक मॉड्यूल:",
        "intro_li1": "* **सुरक्षित क्लिनिकल खाते:** पंजीकरण करें या अपनी सेटिंग्स तक पहुँचें।",
        "intro_li2": "* **दोहरा निदान पाइपलाइन:** मैन्युअल रूप से डेटा दर्ज करें या मेडिकल रिपोर्ट अपलोड करें।",
        "intro_li3": "* **वैश्विक कॉन्फ़िगरेशन मॉड्यूल:** सेटिंग्स ब्लॉक से वास्तविक समय में इंटरफ़ेस बदलें।",
        # Page 2: Auth
        "auth_title": "खाता साइन-इन / लॉगिन",
        "tab_signin": "साइन इन",
        "tab_signup": "नया प्रोफ़ाइल पंजीकृत करें",
        "lbl_fullname": "पूरा नाम",
        "lbl_choose_user": "उपयोगकर्ता नाम चुनें",
        "lbl_choose_pass": "पासवर्ड चुनें",
        "lbl_user": "उपयोगकर्ता नाम",
        "lbl_pass": "पासवर्ड",
        # Page 3: Dashboard
        "dash_title": "मॉडल सटीकता और मूल्यांकन कंसोल",
        "m_auc": "उत्पादन इंजन AUC",
        "m_size": "एकत्रित डेटा का आकार",
        "m_latency": "प्रतिक्रिया समय (लैटेंसी)",
        "m_stable": "स्थिर संस्करण",
        "m_cases": "4,200 मामले",
        "m_ms": "42 एमएस",
        # Page 4: Patient Input
        "input_title": "मरीज के स्वास्थ्य डेटा प्रविष्टि",
        "tab_manual": "मैन्युअल क्लिनिकल प्रविष्टि",
        "tab_upload": "दस्तावेज़ रिपोर्ट अपलोड",
        "form_subtitle": "हृदय स्वास्थ्य पैरामीटर प्रपत्र",
        "age": "उम्र", "gender": "लिंग", "cp": "सीने में दर्द का प्रकार (cp)", "trestbps": "रक्तचाप (mm Hg में trestbps)",
        "chol": "सीरम कोलेस्ट्रॉल (mg/dl में chol)", "fbs": "फास्टिंग ब्लड शुगर > 120 mg/dl (fbs)",
        "restecg": "रेस्टिंग ईसीजी परिणाम (restecg)", "thalach": "अधिकतम हृदय गति (thalach)",
        "exang": "व्यायाम प्रेरित एनजाइना (exang)", "oldpeak": "व्यायाम द्वारा प्रेरित एसटी डिप्रेशन (oldpeak)",
        "slope": "पीक एक्सरसाइज एसटी सेगमेंट का ढलान (slope)", "ca": "फ्लोरोस्कोपी द्वारा रंगीन प्रमुख वाहिकाओं की संख्या (ca)",
        "thal": "थैलेसीमिया का प्रकार (thal)", "male": "पुरुष", "female": "महिला", "true_lbl": "सही", "false_lbl": "गलत",
        "drop_file": "अपनी क्लिनिक PDF, TXT या CSV फाइलें यहाँ ड्राप करें",
        # Page 5: Results
        "results_title": "नैदानिक ​​जोखिम मूल्यांकन और दिशानिर्देश",
        "risk_high": "सिस्टम वर्गीकरण जोखिम सूचकांक के अनुसार आपके लिए जोखिम की संभावना है: ",
        "risk_prob": "% जोखिम संभावना",
        "graph_risk": "हृदय जोखिम %", "graph_clean": "स्वस्थ हृदय %",
        "status_lbl": "स्थिति", "prob_lbl": "संभावना",
        "food_title": "लक्षित आहार आदत और पोषण नियम",
        "food_li1": "* जई (ओट्स) और घुलनशील फाइबर का सेवन बढ़ाएं।\n* खाना पकाने में पूरी तरह से एक्स्ट्रा वर्जिन जैतून के तेल (Olive Oil) का उपयोग करें।\n* दैनिक नमक का सेवन 1,500 मिलीग्राम से कम रखें।",
        "doc_title": "हृदय रोग विशेषज्ञ खोज इंजन",
        "btn_google": "बाहरी निर्देशika से हृदय रोग विशेषज्ञों की खोज करें",
        "export_title": "नैदानिक ​​दस्तावेज़ निर्यात करें",
        "export_p": "अपने क्लिनिकल रिकॉर्ड के लिए इस विश्लेषण की एक पीडीएफ प्रति उत्पन्न और डाउनलोड करें:",
        "note_text": "**नोट:** इस रिपोर्ट पर पूरी तरह भरोसा न करें। यह एक AI जनित और अनुमानित परिणाम है। इसलिए, इस रिपोर्ट का उपयोग अपने नजदीकी अस्पतालों में चर्चा करने या अपने पारिवारिक डॉक्टर से राय लेने के लिए करें।",
        # Settings
        "settings_title": "सिस्टम नियंत्रण और इंटरफ़ेस सेटिंग्स",
        "settings_p": "एप्लिकेशन प्रदर्शन प्राथमिकताओं को कॉन्फ़िगर करें और उपयोगकर्ता सत्र देखें।",
        "set_sub1": "स्थानीयकरण और वैयक्तिकरण",
        "set_lang_lbl": "सिस्टम की प्राथमिक भाषा का चयन",
        "set_theme_lbl": "विजुअल वर्कस्पेस थीम प्रोफाइल",
        "set_sub2": "उपयोगकर्ता सत्र स्थिति प्रोफ़ाइल",
        "set_auth_name": "**प्रमाणित पूरा नाम:** ",
        "set_role": "सौंपी गई भूमिका: क्लिनिकल कोर ऑपरेटर",
        "set_no_profile": "कोई सक्रिय प्रोफ़ाइल नहीं मिली। कृपया खाता लॉगिन पूरा करें।",
        "set_refresh": "दृश्य शैलियों को अपडेट किया गया! ऐप पुनरारंभ हो रहा है...",
        "tab_google": "गूगल लॉगिन",
        "lbl_g_email": "अपना वास्तविक गूगल खाता ईमेल पता दर्ज करें",
        "btn_g_auth": "गूगल के साथ लॉगिन करें"
    }
}